### ISSUE TITLE
Add Captcha Support

### ISSUE THREAD

**Issue by Aspect2222** [pxsty0/discord-token-joiner#2]
Add CapMonster Support, otherwise you can not join any server.

**Comment by pxsty0** [comment]
the code may be added by examining an old code api, thanks for your interest

**Comment by Aspect2222** [comment]
hey, you could add capmonster support they are solving hcaptcha captchas but costs money

**Comment by pxsty0** [comment]
I think a method that everyone can use would be healthier.
